# Generated by Django 3.1 on 2020-09-11 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'db_table': 'categoria_productos',
            },
        ),
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('ciudad', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'transportadora',
                'verbose_name_plural': 'transportadora',
                'db_table': 'transportadora',
            },
        ),
        migrations.CreateModel(
            name='TelefonoTransportadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefono', models.CharField(max_length=15)),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='produccion.transportadora')),
            ],
            options={
                'verbose_name': 'telefono transportadora',
                'verbose_name_plural': 'telefonos transportadoras',
                'db_table': 'telefono_transportadora',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('cantidad', models.CharField(max_length=11)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='produccion.categoriaproductos')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'productos',
            },
        ),
    ]
