# Generated by Django 3.1 on 2020-11-26 02:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateField(default=datetime.datetime.now)),
                ('fechaEntrega', models.DateField()),
                ('fechaRecoleccion', models.DateField()),
                ('ciudad', models.CharField(max_length=25)),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produccion', to='produccion.transportadora')),
            ],
            options={
                'verbose_name': 'orden produccion',
                'verbose_name_plural': 'ordenes produccion',
                'db_table': 'produccion',
            },
        ),
    ]
