# Generated by Django 3.1 on 2020-08-30 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('ciudad', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'transportadora',
                'verbose_name_plural': 'transportadora',
                'db_table': 'transportadoras',
            },
        ),
        migrations.CreateModel(
            name='TelefonoTransportadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefono', models.CharField(max_length=15)),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='produccion.transportadora')),
            ],
            options={
                'verbose_name': 'telefono transportadora',
                'verbose_name_plural': 'telefonos transportadoras',
                'db_table': 'telefono_transportadora',
            },
        ),
    ]
