# Generated by Django 3.1 on 2020-08-31 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_telefonotransportadora_transportadora'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transportadora',
            table='transportadora',
        ),
    ]
