# Generated by Django 3.1 on 2020-08-25 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('ciudad', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='TelefonoProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_telefono', models.CharField(max_length=11)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefono', to='inventario.proveedor')),
            ],
            options={
                'verbose_name': 'telefono',
                'verbose_name_plural': 'telefonos',
                'db_table': 'telefono_proveedor',
            },
        ),
    ]
