# Generated by Django 3.1 on 2020-09-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefonoproveedor',
            name='numero_telefono',
            field=models.CharField(max_length=16),
        ),
    ]
