# Generated by Django 3.1 on 2020-08-30 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20200830_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='unidad_medida',
            field=models.ForeignKey(default='sin categoria', on_delete=django.db.models.deletion.SET_DEFAULT, to='inventario.unidadmedida'),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='nombre',
            field=models.CharField(default='sin categoria', max_length=25),
        ),
    ]
