# Generated by Django 3.1 on 2020-08-31 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20200830_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadmedida',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
    ]
