# Generated by Django 3.1 on 2020-09-10 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_comprainsumos_detallecompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprainsumos',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.proveedor'),
        ),
    ]
