# Generated by Django 3.1 on 2020-09-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_ventas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='estado',
            field=models.CharField(choices=[('cotizacion', 'Cotizacion'), ('venta', 'Venta')], default='', max_length=10),
        ),
    ]
